coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

flags:
  work:
    paths:
      - apps/work/src/
    carryforward: true
